/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.welzuka.platform.codegen.generator.impl;

import com.welzuka.platform.codegen.inbound.Component;
import com.welzuka.platform.codegen.inbound.Entity;
import freemarker.template.Configuration;
import freemarker.template.Template;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class EntityGenerator {
    private static EntityGenerator engine = new EntityGenerator();
    private Template template=null;
    Map<String, Object> dataMap = new HashMap<String, Object>();
    private EntityGenerator()
    {
        init();
    }
    private void init()
    {
        Configuration cfg = new Configuration();
        try {
            cfg.setClassForTemplateLoading(this.getClass(), "/templates/");
            template = cfg.getTemplate("entity.ftl");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }


    public static EntityGenerator get()
    {
        return engine;
    }

    public EntityGenerator buildData(String componentName, Component component,Entity entity, List<String> enums)
    {
        dataMap.put("componentName",componentName);
        dataMap.put("projectName",component.getProjectName());
        entity.getFields().forEach(field -> {
            String[] r = field.fieldName.split("(?=\\p{Upper})");
            String columnName = "";
            for(int i = 0;i<r.length;i++){
                columnName = columnName+r[i];
                if (i!=r.length-1){
                    columnName +="_";
                }
            }
            field.setColumnName(columnName);
        });
        dataMap.put("entity",entity);
        dataMap.put("enums",enums);
        return engine;
    }


    public void  writeFile(String className, Component component, File fileDir)
    {
        File temp = new File("./src/main/java/com/"+component.getProjectName()+"/"
                +component.getComponentName().toLowerCase()+"/"+component.getComponentName().toLowerCase()+"/domain/"+className+".java");
        if (!temp.exists()) {
            Writer fileWriter = null;
            try {
                File file = new File(fileDir.getAbsolutePath() + "/" + className + ".java");
                fileWriter = new FileWriter(file);
                template.process(dataMap, fileWriter);
                fileWriter.flush();
                System.out.println("Generated: " + className + ".java");
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    fileWriter.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

}
